### ISSUE TITLE
Fails if ssh-agent is runnong on the host with Error response from daemon: mkdir /tmp/ssh-agent.sock: file exists.

### ISSUE THREAD

**Issue by robbyoconnor** [kylemanna/docker-aosp#14]
```
rob at rob-LAPTOP in ~/aosp 
$ bash ./build-marshmallow.sh 
+ '[' '' = docker ']'
+ aosp_url=https://raw.githubusercontent.com/kylemanna/docker-aosp/master/utils/aosp
+ args='bash run.sh docker'
+++ dirname ./build-marshmallow.sh
++ cd .
++ pwd -P
++ basename ./build-marshmallow.sh
+ export 'AOSP_EXTRA_ARGS=-v /home/rob/aosp/build-marshmallow.sh:/usr/local/bin/run.sh:ro'
+ AOSP_EXTRA_ARGS='-v /home/rob/aosp/build-marshmallow.sh:/usr/local/bin/run.sh:ro'
+ export AOSP_IMAGE=kylemanna/aosp:6.0-marshmallow
+ AOSP_IMAGE=kylemanna/aosp:6.0-marshmallow
+ '[' -n '' ']'
+ '[' -x ../utils/aosp ']'
++ type -P aosp
+ '[' -n '' ']'
++ type -P curl
+ '[' -n /usr/bin/curl ']'
+ bash /dev/fd/63 bash run.sh docker
++ curl -s https://raw.githubusercontent.com/kylemanna/docker-aosp/master/utils/aosp
aosp: Checking if /home/rob/aosp exists
aosp: Checking if /home/rob/aosp exists - ok
aosp: Checking if /home/rob/ccache exists
aosp: Checking if /home/rob/ccache exists - ok

docker: Error response from daemon: mkdir /tmp/ssh-agent.sock: file exists.
```

**Comment by kylemanna** [comment]
Looks like your code is [tripping on the docker run mapping of the ssh agent](https://github.com/kylemanna/docker-aosp/blob/ab9f7515dd97bf041684445bb33c0d5261e2d93f/utils/aosp#L47-L55)

Docker shouldn't have a problem with this on recent versions [as the Docker docs give a similar example with the Docker daemon socket](https://docs.docker.com/engine/reference/commandline/run/#/mount-volume--v---read-only).

What does the output of `docker info` say?

**Comment by robbyoconnor** [comment]
$ docker info 
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 53
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 66
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58 GiB
Name: rob-LAPTOP
ID: TUNW:HAUX:OY5R:QPB6:ZWBF:SVYW:4NKL:6D3I:RJZ2:PNNA:HBMQ:TR36
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: robbyoconnor
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by kylemanna** [comment]
Is this still a problem?

**Comment by kylemanna** [comment]
Also, can you verify that your `$SSH_AUTH_SOCK` exists and is something sane?  Looks like the Docker is trying to create a directory when it shouldn't be.

Run:

    ls -l $SSH_AUTH_SOCK

**Comment by robbyoconnor** [comment]
`ls -l $SSH_AUTH_SOCK
lrwxrwxrwx 1 rob rob 26 Jan  1 09:18 /tmp/ssh-agent.sock -> /run/user/1000/keyring/ssh`

**Comment by kylemanna** [comment]
Ahh, the problem is that it's a symlink, can you run

    SSH_AUTH_SOCK=/run/user/1000/keyring/ssh

and try the build again?

**Comment by robbyoconnor** [comment]
I haven't even used this yet -- been meaning to build a custom ROM for myself but been lazy I'm going to close this (I can always re-open if the issue pops up again)

**Comment by kylemanna** [comment]
Sounds good, thanks for the update.
