### ISSUE TITLE
what happen

### ISSUE THREAD

**Issue by hhhaiai** [kylemanna/docker-aosp#46]
Unable to find image 'kylemanna/docker-aosp:latest' locally
docker: Error response from daemon: manifest for kylemanna/docker-aosp:latest not found.
See 'docker run --help'

**Comment by kylemanna** [comment]
I think you typo'd, should be `kylemanna/aosp:latest`

    ~ ❯❯❯ docker run --rm -it kylemanna/aosp:latest
    Unable to find image 'kylemanna/aosp:latest' locally
    latest: Pulling from kylemanna/aosp
    35b42117c431: Already exists
    ad9c569a8d98: Already exists
    293b44f45162: Already exists
    0c175077525d: Already exists
    3b21680197d0: Pull complete
    e4332d6a4fc8: Pull complete
    a27ff9d816aa: Pull complete
    8dc0f3f7ba1e: Pull complete
    2aebf5a90e4e: Pull complete
    85d47328098d: Pull complete
    25381d6af343: Pull complete
    2c8ef9625823: Pull complete
    Digest: sha256:ce582b47a2d31116e6c41d12e7a6381d03d00a8401523b54500943dd7dcbed9a
    Status: Downloaded newer image for kylemanna/aosp:latest
    docker_entrypoint: Creating user UID/GID [1000/1000]
    docker_entrypoint: Creating user UID/GID [1000/1000] - done
    docker_entrypoint: Copying .gitconfig and .ssh/config to new user home
    docker_entrypoint: Copying .gitconfig and .ssh/config to new user home - done
    docker_entrypoint: Creating /tmp/ccache and /aosp directory
    docker_entrypoint: Creating /tmp/ccache and /aosp directory - done
 
    aosp@ae92152adfe3:/aosp$

**Comment by hhhaiai** [comment]
kylemanna/aosp:7.0-nougat .  has newest ?

**Comment by kylemanna** [comment]
Sure, still old though.

**Comment by hhhaiai** [comment]
> Sure, still old though.

kylemanna/aosp:latest. got it~ WOW~
